### ISSUE TITLE
Screen scraping problem in fetch_zones

### ISSUE THREAD

**Issue by jeffjumper** [rsnodgrass/pyadtpulse#6]
Hi Ryan. Thanks for putting this integration together. It has worked well for me for the past 6 months in my production HA instance. I just tried to set up a new instance to do some testing of the new HA scripting features and ran into a problem with the latest version of the HACS integration.

I'm getting the following error:

> 2020-10-14 19:08:29 ERROR (MainThread) [homeassistant.setup] Error during setup of component adtpulse
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/adtpulse/__init__.py", line 58, in setup
    service = PyADTPulse(username, password)
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/__init__.py", line 42, in __init__
    self.login()
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/__init__.py", line 140, in login
    self._update_sites(response.text)
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/__init__.py", line 77, in _update_sites
    self._initialize_sites(soup)
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/__init__.py", line 100, in _initialize_sites
    sites.append( ADTPulseSite(self, site_id, site_name, soup) )
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/site.py", line 43, in __init__
    self._update_alarm_status(summary_html_soup)
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/site.py", line 142, in _update_alarm_status
    self.fetch_zones()
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/site.py", line 164, in fetch_zones
    device_id = re.findall(regexDevice, onClickValueText)[0]
IndexError: list index out of range

It looks like you're expecting lines in the HTML table on that page to look like this:
`<tr class='p_listRow'  onClick="goToUrl('device.jsp?id=1');">`

But I have a line for my ADT Pulse Gateway in the table that looks like this:
`<tr class='p_listRow'  onClick="goToUrl('gateway.jsp');">`
...which doesn't match your regex.

Let me know if you need any other information from me.

Thanks again!
--Jeff

**Comment by rsnodgrass** [comment]
Can you try updating to the 'master' version?  I don't know this section of pyadtpulse code well yet since it was a recent contribution, but I added a check that skips any results that don't match the required device.jsp regexps.  This should at least stop it crashing.

**Comment by jeffjumper** [comment]
I see the new debug message in the log but still got an error:

>2020-10-15 08:54:59 DEBUG (SyncWorker_6) [pyadtpulse] Attempting GET https://portal.adtpulse.com/myhome/20.0.0-221/ajax/orb.jsp (try 1/3)
2020-10-15 08:54:59 DEBUG (SyncWorker_6) [pyadtpulse] Attempting GET https://portal.adtpulse.com/myhome/20.0.0-221/system/system.jsp (try 1/3)
2020-10-15 08:55:00 DEBUG (SyncWorker_6) [pyadtpulse] Attempting GET https://portal.adtpulse.com/myhome/20.0.0-221/system/device.jsp?id=1 (try 1/3)
2020-10-15 08:55:00 DEBUG (SyncWorker_6) [pyadtpulse.site] Failed regex match #goToUrl\('device.jsp\?id=(\d*)'\); on #goToUrl('gateway.jsp'); from ADT Pulse service, ignoringsy
2020-10-15 08:55:00 ERROR (MainThread) [homeassistant.setup] Error during setup of component adtpulse
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/adtpulse/__init__.py", line 58, in setup
    service = PyADTPulse(username, password)
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/__init__.py", line 42, in __init__
    self.login()
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/__init__.py", line 140, in login
    self._update_sites(response.text)
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/__init__.py", line 77, in _update_sites
    self._initialize_sites(soup)
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/__init__.py", line 100, in _initialize_sites
    sites.append( ADTPulseSite(self, site_id, site_name, soup) )
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/site.py", line 43, in __init__
    self._update_alarm_status(summary_html_soup)
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/site.py", line 142, in _update_alarm_status
    self.fetch_zones()
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/site.py", line 172, in fetch_zones
    device_id = result[0]
IndexError: list index out of range

**Comment by rsnodgrass** [comment]
Master should fix this.    I haven’t released the new version yet.   
  
  
  
    
  

  
  
>

**Comment by jeffjumper** [comment]
Thanks for the fix!
